name: Update SUMMARY.md

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # ensures the token from this job (with write perms) is used
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate SUMMARY.md
        run: |
          python3 scripts/generate_summary.py

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): auto-update SUMMARY.md"
          file_pattern: SUMMARY.md
          # pushes back to the same branch that triggered the job
          branch: ${{ github.ref_name }}
